document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1, shrink-to-fit=no\'>");
document.writeln("    <title>foot</title>");
// document.writeln("    <link rel=\'stylesheet\' href=\'../lib/css/bootstrap.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/foot.css\'>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\'w_foot\'>");
document.writeln("    <div class=\'w_foot_in\'>");
document.writeln("        <div class=\'w_foot_left\'>");
document.writeln("            <div class=\'w_text\'>");
document.writeln("                扫我有惊喜");
document.writeln("            </div>");
document.writeln("            <div class=\'w_ercode\'>");
document.writeln("");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'w_line\'></div>");
document.writeln("        <div class=\'w_foot_right\'>");
document.writeln("            <ul class=\'w_ul\'>");
document.writeln("                <li>");
document.writeln("                    <span>");
document.writeln("                    关于我们");
document.writeln("                    </span>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'../html/su_our.html\'>关于我们</a></li>");
document.writeln("                        <li><a href=\'\'>加入我们</a></li>");
document.writeln("                        <li><a href=\'\'>联系我们</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li><span>");
document.writeln("                    关注我们");
document.writeln("                </span>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'\'>新浪微博</a></li>");
document.writeln("                        <li><a href=\'\'>微信公众号</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li><span>");
document.writeln("                    友情链接");
document.writeln("                </span>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'\'>腾讯网</a></li>");
document.writeln("                        <li><a href=\'\'>新浪网</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        <div class=\'w_foot_bottom\'>");
document.writeln("            ©2018 just2017.cn 版权所有。鲁ICP备18038759号");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
// document.writeln("<script src=\'..js/jquery-3.3.1.js\'></script>");
document.writeln("<script src=\'../lib/js/bootstrap.min.js\'></script>");
document.writeln("</body>");
document.writeln("</html>");