document.writeln("<div class=\'s_header\'>");
document.writeln("        <img src=\'../images/logo.png\' alt=\'\'>");
document.writeln("        <span class=\'s_header_name\'>随享</span>");
document.writeln("        <input type=\'text\' class=\'s_header_search\'>");
document.writeln("        <span class=\'s_header_searchp\'><i class=\'layui-icon layui-icon-search\' style=\'font-size: 30px;\'></i></span>");
document.writeln("        <ul class=\'layui-nav s_header_right\' id=\'s_header_right\' style=\'background-color: #FFFFFF\'>");
document.writeln("            <li class=\'layui-nav-item\'>");
document.writeln("                <a href=\'\'><i class=\'layui-icon\' style=\'font-size: 30px;color: #87c4db\' id=\'s_header_right_shouye\'>&#xe68e;</i></a>");
document.writeln("            </li>");
document.writeln("            <li class=\'layui-nav-item\'>");
document.writeln("                <a href=\'\'><i class=\'layui-icon\' style=\'font-size: 30px;color: #87c4db\' id=\'s_header_right_xiaoxi\'>&#xe645;</i></a>");
document.writeln("                <dl class=\'layui-nav-child\'>");
document.writeln("                    <dd><a href=\'focus.html\' target=\'_blank\'>通知</a></dd>");
document.writeln("                </dl>");
document.writeln("            </li>");
document.writeln("            <li class=\'layui-nav-item\'>");
document.writeln("                <a href=\'\'><i class=\'layui-icon\' style=\'font-size: 30px;color: #87c4db\' id=\'s_header_right_shezhi\'>&#xe716;</i></a>");
document.writeln("                <dl class=\'layui-nav-child\'>");
document.writeln("                    <dd><a href=\'backgroud.html\'>更换背景</a></dd>");
document.writeln("                    <dd><a href=\'\' id=\'s_quit\'>退出</a></dd>");
document.writeln("                    <dd><a href=\'information.html\'>账号设置</a></dd>");
document.writeln("                </dl>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");